//All valid statuses for a job application
export type ApplicationStatus =
  | "Interested"
  | "Applied"
  | "Interview"
  | "Rejected"
  | "Evaluation"
  | "No Response";

//represents a complete job application record returned from the backend
//ID is generated by the database
export type JobApplication = {
  id: number;
  company: string;
  position: string;
  status: ApplicationStatus;
  location: string;
  dateApplied: string;
  jobUrl: string;
  salary: string;
  notes: string;
};

//Represents the data required to create a new application
export type NewJobApplication = Omit<JobApplication, "id">;